### ISSUE TITLE
Creating New Ms Records for the EMIP CUA Weiner Collection

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Manuscripts#1109]
In creating new records for the EMIP CUA Weiner collection, I note here https://betamasaheft.eu/manuscripts/INS0005IHA/list?per-page=20&start=181& that the repository reference is  INS0005IHA, whereas others have INS0447EMIP. I am concerned that there is consistency here, and would appreciate advice.

**Comment by PietroLiuzzo** [comment]
Dear Ralph, there are many such duplicates in the IslHornAfr Data. We do not have at the moment resources to fix this in that dataset. please use the institution record which does not end with IHA, those will be aligned and replaced as soon as it will be possible to do so.

**Comment by Ralph-Lee-UK** [comment]
Clear, I have just made a pull request that will have some errors in this respect - I will correct them in the next set of edits

**Comment by PietroLiuzzo** [comment]
no worries. thanks for letting me know.

**Comment by Ralph-Lee-UK** [comment]
And a final question. The first record, EMIP02714 was created in the app, and so resides in the 'new' folder. Should I leave this to you to move into the EMIP folder, or is that something to leave to you?

**Comment by PietroLiuzzo** [comment]
there exists a third possibility to do it without my intervention :) you can simply move the file in its correct location and commit that change together with the others. Thanks!
