### ISSUE TITLE
Additional character `ወ` to be removed   ተግሣጽ፡ፍካሬ፡ ዘጻድቃን፡ ወዘኃጢአን። መዝሙር፡ ዘዳዊት፡ ሃሌ፡ ሉያ። ፩ ፩

### ISSUE THREAD

**Issue by Hasnake** [BetaMasaheft/Manuscripts#1275]
https://github.com/BetaMasaheft/Manuscripts/blob/6e7309c75cbb04194eaac91d87a641b31151d460/PrivateCollections/Germany/CJN/CJN002.xml#L48

**Comment by Hasnake** [comment]
ተግሣጽ፡ፍካሬ፡ ዘጻድቃን፡ ወዘኃጢአን። **ወ** መዝሙር፡ ዘዳዊት፡ ሃሌ፡ ሉያ። ፩ ፩ 
**ወ** to be removed

**Comment by Getinet309** [comment]
'ጢ' should change with 'ጥ' to be ተግሣጽ፡ፍካሬ፡ ዘጻድቃን፡ ወዘኃጥአን።

**Comment by Hasnake** [comment]
> 'ጢ' should change with 'ጥ' to be ተግሣጽ፡ፍካሬ፡ ዘጻድቃን፡ ወዘኃጥአን።

You are right,  @Getinet309 .I saw the manuscript and it is correct there.

@PietroLiuzzo , Please review the comments and update the file.

**Comment by PietroLiuzzo** [comment]
Dear Hasnake, thanks for your input, you can update the file yourself and someone, perhaps not me, will review a Pull Request with those changes.

**Comment by Hasnake** [comment]
Thank you so much for the help, my professor, Pietro.
I made a pull request as you suggested to me and again thank you for
walking me through it.

Regards
Haile

**Comment by PietroLiuzzo** [comment]
Thanks to you! I have added also a change element with your initials (HAs), so that your contribution is more visible.

**Comment by Hasnake** [comment]
Thank You so much
