### ISSUE TITLE
ወእምንዳቤየ፡ ዕርኀበ፡ ሊተ to be ወእምንዳቤየ፡ አርኀበ፡ ሊተ

### ISSUE THREAD

**Issue by Hasnake** [BetaMasaheft/Manuscripts#1276]
https://github.com/BetaMasaheft/Manuscripts/blob/6e7309c75cbb04194eaac91d87a641b31151d460/PrivateCollections/Germany/CJN/CJN002.xml#L71

**Comment by PietroLiuzzo** [comment]
Dear @Hasnake I am not sure what is this, perhaps another correction? please, simply make that correction in the file and propose the Pull Request for review. Thanks!

**Comment by PietroLiuzzo** [comment]
see https://github.com/BetaMasaheft/Manuscripts/pull/1278. Thanks!
