### ISSUE TITLE
Problem with Transkribus text file 

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Manuscripts#1953]
I have been checking the code and display of text, following up on the formatting issues that we had before with the scrolls - and I have been systematically adding corrected transkribus output files in the last few pull requests, as you know. 

I took a look today at EMIPms00493, and there is still a problem. I think I may have missed something, but perhaps you can help me. 

The text in the 'text' file following the XLS transformation is:
![image](https://user-images.githubusercontent.com/39619238/209114429-8ed871ad-3829-40f4-b381-de2f7d89dd50.png)

But when I look at the TEI/XML code from the web page it looks like this (which corresponds to what is displayed on the web page)
![image](https://user-images.githubusercontent.com/39619238/209114649-8b892ce2-22ae-4ba2-8638-ef0992aee93a.png)

I am a little confused as to how this could arise. Any advice most welcome!

**Comment by eu-genia** [comment]
probably the syncing did not go through properly, I have reexpanded manually the file, should be OK now, please check and close if all is good

**Comment by Ralph-Lee-UK** [comment]
Now working. Thanks!
