### ISSUE TITLE
Two items with the ID EMML 6952

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Manuscripts#2060]
@eu-genia 
When looking up EMML6952, something has gone wrong:

---
Something has gone wrong and there are more than one item with id EMML6952.

/db/apps/expanded/manuscripts/EMML/6001-7000/EMML6952/EMML6952.xml
/db/apps/expanded/manuscripts/EMML/6001-7000/EMML6952/EMML6952text.xml
---

**Comment by eu-genia** [comment]
this always happens when merging documents with transcription separately, fixed
