### ISSUE TITLE
Ms stub for Tübingen, Universitätsbibliothek Tübingen, Tübingen Aeth. 28 

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Manuscripts#2682]
Hello! I would like to have a stub for Tübingen, Universitätsbibliothek Tübingen, Tübingen Aeth. 28 , because to have it in the list of witnesses. Can someone create it for me or shall I do it myself? In general, can I mention a witness without having a stub? If yes, what would be the right way?
Thank you very much!

**Comment by MassimoVilla** [comment]
Please @nafisa-valieva feel free to create a stub and assign the PR to me if you need
