### ISSUE TITLE
ESap038 - Ruling pattern not correctly displayed

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Manuscripts#416]
The ruling pattern A-1A-1A1A/0-0/0-0/B (the second pattern in this description) is not correctly displayed in the entry of ESap038 (https://betamasaheft.eu/manuscripts/ESap038/main).
Clicking on this pattern leads to error message: http://palaeographia.org/muzerelle/regGraph2.php?F=1A-1A-1A1A/0-0/0-0/B

**Comment by PietroLiuzzo** [comment]
I see only a pattern 1A-1A-1A1A/0-0/0-0/B which looks like the one you wrote. It looks to me to be correct, and I do not understand what the incorrectness should be. The link seems to work correctly as well. if the pattern in itself is wrong, I do not know, but it seems to be what the error through by the website of Muzerelle points to the B. I think that is also correct. Is an extension B,  actually possible for verticals in 1A-1A-1A1A? should it not be something like 1-11-11, for an extension B to be possible? fixing the pattern structure to the correct one will likely also return the correct view for the correct pattern in Muzerelle's website. 
Please let me know if I have missed the point of the incorrectness here.

**Comment by SusanneHummel** [comment]
hm, if I click on the ruling pattern  1A-1A-1A1A/0-0/0-0/B, I am forwarded to this:
![screenshot](https://user-images.githubusercontent.com/28757489/81580324-9401e980-93ad-11ea-8a93-1abf4b60e8bb.jpg)

If I click, on the other two patterns, I am forwarded to the nice figures.

**Comment by PietroLiuzzo** [comment]
exactly. and this is correct, the B in the pattern is likely to be wrong. there is no marginal vertical, so there cannot be an extension B for the fourth section of the pattern

**Comment by SusanneHummel** [comment]
But as far as I uderstood, 

A, B and C refer to the length of the horizontal lines? 

All thre start from the innserside of the leaf but end differntly:
A reaches the edge
B reaches the pricks
C reaches the last columne line. 

Maybe I misunderstood???

**Comment by SusanneHummel** [comment]
I checked again: We formulated the pattern as described above in the Ethio-Spare project. It might not be correct, but then many patterns are wrong, I fear.

**Comment by PietroLiuzzo** [comment]
I think in the pattern, if a vertical line is not present, then the extension is not considered. I have no experience or knowledge of this at all, I have just followed the link under the error message and read the presentation there. If I understand well this slide http://palaeographia.org/muzerelle/reglure.htm?P=9 extension B goes to a margin vertical line which needs to be declared in the first part of the pattern to be used. so you need to have 1-11-11 to be able to have an extension B, with 1-1-11 as in the example above, there is no reference for an extension B, only for A or C

**Comment by SusanneHummel** [comment]
Thank you! But somehow, the description is not clear to me (sorry!)

I would need this pattern here: palaeographia.org/muzerelle/regGraph2.php?F=1-11-11/0/0/B

I don't understand why there is no A before 1. But the B here is correct (the horizontal lines end in the pricks)

However, I copy below for comparison all the three basic ruling patterns in Ethiopic Mss (but I am not an expert as well!). I don't understand why the formula with B is different than with A and C at the end. But I can write '1-11-11/0/0/B' in my description.

![1A-1A-1A1A:0-0:0-0:A](https://user-images.githubusercontent.com/28757489/81584571-31135100-93b3-11ea-97e0-e8d9c6ed122e.jpg)

![1-11-11:0:0:B](https://user-images.githubusercontent.com/28757489/81584584-35d80500-93b3-11ea-9070-8dd65378c62b.jpg)

![1A-1A-1A1A:0-0:0-0:C](https://user-images.githubusercontent.com/28757489/81584597-396b8c00-93b3-11ea-9ca2-97a7c5f4f7b9.jpg)

**Comment by PietroLiuzzo** [comment]
yes, as written above you need 1-11-11, or 1A-1A1A-1A1A to be able to have a B extension. I did not find any reference to pricks in Muzerelle description, the B extension goes from the outer margin to the margin vertical line, which is declared in the second position of the second segment. if this is not there (the second 1 after the first -) then there cannot be such extent and Muzzerelle's website very rightly points to that error.

**Comment by SusanneHummel** [comment]
Thank you!
