### ISSUE TITLE
a tiny error in the guideline?

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Manuscripts#5]
Bonjour,
I am right to assume that for the text encoding, instead of 
<del rend=erasure> I write <del rend="erasure">, i.e. add (")(")?
I find the description a bit inconsistant in terms of using "" or '' or absence if any.  
Assume that no discussion is needed on this point, just decision the to follow.
thank you!

**Comment by eu-genia** [comment]
Sorry Nafisa, maybe it is because of my cold, but I did not understand the question...
The HLCES style in English is single quotation marks if that is what is asked.

**Comment by nafisa-valieva** [comment]
I am sorry for your cold. I am not good at writing an issue just, all the examples I wrote in it appeared deleted. 
No, I am not asking about the style, but for the tags,  the Guidelines  for text encoding is inconsistent at this point, some tags as written do not work. I think it needs to be revised

**Comment by eu-genia** [comment]
you have to provide examples
if you want to post the code, select it and then click the button < > above.
or a link to the page you have problems with.

**Comment by nafisa-valieva** [comment]
here the examples:
('')`<hi` rend='negative'>`
("")`<del rend="expunctuated">`
no `<del rend=erasure>`
I wanted to tag "erasure" and decided to inform you about this tiny problem.

**Comment by eu-genia** [comment]
yes, there is an error in the guidelines, now corrected (in TEI XML all attributes are given between double quotation marks, so it should be hi rend="negative" del rend="erasure" etc.)
