### ISSUE TITLE
persName

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Manuscripts#6]
Hi! I apologize if I am repeating the same question that was already discussed. Either I do not know where to find an issue on this point or it was not written yet.
I have a persName of a certain king, but I have two possible interpretation, I would like to give ref to both indicate cert as unknown. Is it possibly to modify the schema, making more than one ref possible or what would be the solution for such cases?
`<persName ref="PRS6152Lalibala" ref="PRS4327GabraMa"cert="unknown">ገብረ፡መስቀል፡</persName>`
thank you!

**Comment by PietroLiuzzo** [comment]
please check the section about certainty in the page of the guidelines about named entities 
https://betamasaheft.eu/Guidelines/?q=named%20entities&start=11&id=named-entities-and-authority-lists
the use of certainty is the same for persName as it is for placeName.
